using MediatR;
using ProConnect_Backend.Application.DTOsResponse.ProfessionalProfileDTOs;
using ProConnect_Backend.Domain.DTOsRequest.ProfessionalProfileDTOs;

namespace ProConnect_Backend.Application.UseCases.ProfessionalProfile.Commands.UpdateProfessionalProfile;

public record UpdateProfessionalProfileCommand(uint ProfileId, UpdateProfessionalProfileDto Dto) : IRequest<ProfessionalProfileResponseDto>;
