// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProConnect_Backend.Infrastructure.Data;

#nullable disable

namespace ProConnect_Backend.Infrastructure.Migrations
{
    [DbContext(typeof(ProConnectDbContext))]
    partial class ProConnectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProConnect_Backend.Domain.Entities.Payment", b =>
                {
                    b.Property<uint>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("payment_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("PaymentId"));

                    b.Property<string>("Method")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("method");

                    b.Property<DateTime>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("payment_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<uint>("SessionId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Pending'");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("PaymentId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PaymentDate" }, "payments_payment_date_index");

                    b.HasIndex(new[] { "SessionId" }, "payments_session_id_index");

                    b.HasIndex(new[] { "Status" }, "payments_status_index");

                    b.HasIndex(new[] { "Status", "PaymentDate" }, "payments_status_payment_date_index");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("ProConnect_Backend.Domain.Entities.ProfessionalProfile", b =>
                {
                    b.Property<uint>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("profile_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("ProfileId"));

                    b.Property<string>("Experience")
                        .HasMaxLength(600)
                        .HasColumnType("varchar(600)")
                        .HasColumnName("experience");

                    b.Property<string>("Headline")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("headline");

                    b.Property<uint>("SpecialtyId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("specialty_id");

                    b.Property<uint>("UserId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("ProfileId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SpecialtyId" }, "professional_profiles_specialty_id_index");

                    b.HasIndex(new[] { "UserId" }, "professional_profiles_user_id_unique")
                        .IsUnique();

                    b.ToTable("professional_profiles", (string)null);
                });

            modelBuilder.Entity("ProConnect_Backend.Domain.Entities.Review", b =>
                {
                    b.Property<uint>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("review_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("ReviewId"));

                    b.Property<uint>("ClientId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("client_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("comment");

                    b.Property<uint>("ProfessionalId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("professional_id");

                    b.Property<decimal>("Rating")
                        .HasPrecision(2, 2)
                        .HasColumnType("decimal(2,2)")
                        .HasColumnName("rating");

                    b.Property<DateTime>("ReviewDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("review_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<uint>("SessionId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("session_id");

                    b.HasKey("ReviewId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ClientId" }, "reviews_client_id_index");

                    b.HasIndex(new[] { "ProfessionalId" }, "reviews_professional_id_index");

                    b.HasIndex(new[] { "Rating" }, "reviews_rating_index");

                    b.HasIndex(new[] { "ReviewDate" }, "reviews_review_date_index");

                    b.HasIndex(new[] { "SessionId" }, "reviews_session_id_foreign");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("ProConnect_Backend.Domain.Entities.RevokedToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("jti");

                    b.Property<DateTime>("RevokedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("revoked_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ExpiresAt" }, "revoked_tokens_expires_at_index");

                    b.HasIndex(new[] { "Jti" }, "revoked_tokens_jti_unique")
                        .IsUnique();

                    b.ToTable("revoked_tokens", (string)null);
                });

            modelBuilder.Entity("ProConnect_Backend.Domain.Entities.Scheduled", b =>
                {
                    b.Property<uint>("AvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("availability_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("AvailabilityId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("end_date");

                    b.Property<uint>("SessionId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("start_date");

                    b.HasKey("AvailabilityId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SessionId" }, "scheduleds_session_id_foreign");

                    b.ToTable("scheduleds", (string)null);
                });

            modelBuilder.Entity("ProConnect_Backend.Domain.Entities.Session", b =>
                {
                    b.Property<uint>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("session_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("SessionId"));

                    b.Property<uint>("ClientId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("end_date");

                    b.Property<string>("MeetUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("meet_url");

                    b.Property<uint>("ProfessionalId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("professional_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("status");

                    b.HasKey("SessionId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ClientId" }, "sessions_client_id_foreign");

                    b.HasIndex(new[] { "ProfessionalId" }, "sessions_professional_id_foreign");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("ProConnect_Backend.Domain.Entities.Specialty", b =>
                {
                    b.Property<uint>("SpecialtyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("specialty_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("SpecialtyId"));

                    b.Property<string>("Description")
                        .HasMaxLength(600)
                        .HasColumnType("varchar(600)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("SpecialtyId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "specialties_name_unique")
                        .IsUnique();

                    b.ToTable("specialties", (string)null);
                });

            modelBuilder.Entity("ProConnect_Backend.Domain.Entities.User", b =>
                {
                    b.Property<uint>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("user_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("photo_url");

                    b.Property<DateTime>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("registration_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("role");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "users_email_unique")
                        .IsUnique();

                    b.HasIndex(new[] { "RegistrationDate" }, "users_registration_date_index");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ProConnect_Backend.Domain.Entities.Verification", b =>
                {
                    b.Property<uint>("VerificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("verification_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("VerificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Pending'");

                    b.Property<uint>("UserId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("VerificationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("verification_date");

                    b.HasKey("VerificationId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CreatedAt" }, "verifications_created_at_index");

                    b.HasIndex(new[] { "Status" }, "verifications_status_index");

                    b.HasIndex(new[] { "UserId" }, "verifications_user_id_index");

                    b.HasIndex(new[] { "VerificationDate" }, "verifications_verification_date_index");

                    b.ToTable("verifications", (string)null);
                });

            modelBuilder.Entity("ProConnect_Backend.Domain.Entities.VerificationDocument", b =>
                {
                    b.Property<uint>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("document_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("DocumentId"));

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("document_type");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("file_url");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<uint>("VerificationId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("verification_id");

                    b.HasKey("DocumentId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DocumentType" }, "verification_documents_document_type_index");

                    b.HasIndex(new[] { "UploadedAt" }, "verification_documents_uploaded_at_index");

                    b.HasIndex(new[] { "VerificationId" }, "verification_documents_verification_id_index");

                    b.ToTable("verification_documents", (string)null);
                });

            modelBuilder.Entity("ProConnect_Backend.Domain.Entities.WeeklyAvailability", b =>
                {
                    b.Property<uint>("WeeklyAvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("weekly_availability_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("WeeklyAvailabilityId"));

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("end_date_time");

                    b.Property<uint>("ProfessionalId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("professional_id");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("start_date_time");

                    b.Property<string>("WeekDay")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("week_day")
                        .HasDefaultValueSql("'DEFAULT TRUE'");

                    b.HasKey("WeeklyAvailabilityId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ProfessionalId", "StartDateTime", "EndDateTime" }, "professional_id_start_date_time_end_date_time_index");

                    b.HasIndex(new[] { "EndDateTime" }, "weekly_availabilities_end_date_time_index");

                    b.HasIndex(new[] { "ProfessionalId" }, "weekly_availabilities_professional_id_index");

                    b.HasIndex(new[] { "StartDateTime" }, "weekly_availabilities_start_date_time_index");

                    b.HasIndex(new[] { "WeekDay" }, "weekly_availabilities_week_day_index");

                    b.ToTable("weekly_availabilities", (string)null);
                });

            modelBuilder.Entity("ProConnect_Backend.Domain.Entities.Payment", b =>
                {
                    b.HasOne("ProConnect_Backend.Domain.Entities.Session", "Session")
                        .WithMany("Payments")
                        .HasForeignKey("SessionId")
                        .IsRequired()
                        .HasConstraintName("payments_session_id_foreign");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ProConnect_Backend.Domain.Entities.ProfessionalProfile", b =>
                {
                    b.HasOne("ProConnect_Backend.Domain.Entities.Specialty", "Specialty")
                        .WithMany("ProfessionalProfiles")
                        .HasForeignKey("SpecialtyId")
                        .IsRequired()
                        .HasConstraintName("professional_profiles_specialty_id_foreign");

                    b.HasOne("ProConnect_Backend.Domain.Entities.User", "User")
                        .WithOne("ProfessionalProfile")
                        .HasForeignKey("ProConnect_Backend.Domain.Entities.ProfessionalProfile", "UserId")
                        .IsRequired()
                        .HasConstraintName("professional_profiles_user_id_foreign");

                    b.Navigation("Specialty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProConnect_Backend.Domain.Entities.Review", b =>
                {
                    b.HasOne("ProConnect_Backend.Domain.Entities.User", "Client")
                        .WithMany("ReviewClients")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("reviews_client_id_foreign");

                    b.HasOne("ProConnect_Backend.Domain.Entities.User", "Professional")
                        .WithMany("ReviewProfessionals")
                        .HasForeignKey("ProfessionalId")
                        .IsRequired()
                        .HasConstraintName("reviews_professional_id_foreign");

                    b.HasOne("ProConnect_Backend.Domain.Entities.Session", "Session")
                        .WithMany("Reviews")
                        .HasForeignKey("SessionId")
                        .IsRequired()
                        .HasConstraintName("reviews_session_id_foreign");

                    b.Navigation("Client");

                    b.Navigation("Professional");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ProConnect_Backend.Domain.Entities.Scheduled", b =>
                {
                    b.HasOne("ProConnect_Backend.Domain.Entities.Session", "Session")
                        .WithMany("Scheduleds")
                        .HasForeignKey("SessionId")
                        .IsRequired()
                        .HasConstraintName("scheduleds_session_id_foreign");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ProConnect_Backend.Domain.Entities.Session", b =>
                {
                    b.HasOne("ProConnect_Backend.Domain.Entities.User", "Client")
                        .WithMany("SessionClients")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("sessions_client_id_foreign");

                    b.HasOne("ProConnect_Backend.Domain.Entities.User", "Professional")
                        .WithMany("SessionProfessionals")
                        .HasForeignKey("ProfessionalId")
                        .IsRequired()
                        .HasConstraintName("sessions_professional_id_foreign");

                    b.Navigation("Client");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("ProConnect_Backend.Domain.Entities.Verification", b =>
                {
                    b.HasOne("ProConnect_Backend.Domain.Entities.User", "User")
                        .WithMany("Verifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("verifications_user_id_foreign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProConnect_Backend.Domain.Entities.VerificationDocument", b =>
                {
                    b.HasOne("ProConnect_Backend.Domain.Entities.Verification", "Verification")
                        .WithMany("VerificationDocuments")
                        .HasForeignKey("VerificationId")
                        .IsRequired()
                        .HasConstraintName("verification_documents_verification_id_foreign");

                    b.Navigation("Verification");
                });

            modelBuilder.Entity("ProConnect_Backend.Domain.Entities.WeeklyAvailability", b =>
                {
                    b.HasOne("ProConnect_Backend.Domain.Entities.User", "Professional")
                        .WithMany("WeeklyAvailabilities")
                        .HasForeignKey("ProfessionalId")
                        .IsRequired()
                        .HasConstraintName("weekly_availabilities_professional_id_foreign");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("ProConnect_Backend.Domain.Entities.Session", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Reviews");

                    b.Navigation("Scheduleds");
                });

            modelBuilder.Entity("ProConnect_Backend.Domain.Entities.Specialty", b =>
                {
                    b.Navigation("ProfessionalProfiles");
                });

            modelBuilder.Entity("ProConnect_Backend.Domain.Entities.User", b =>
                {
                    b.Navigation("ProfessionalProfile");

                    b.Navigation("ReviewClients");

                    b.Navigation("ReviewProfessionals");

                    b.Navigation("SessionClients");

                    b.Navigation("SessionProfessionals");

                    b.Navigation("Verifications");

                    b.Navigation("WeeklyAvailabilities");
                });

            modelBuilder.Entity("ProConnect_Backend.Domain.Entities.Verification", b =>
                {
                    b.Navigation("VerificationDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
